stayintarkov/SIT.Manager.Avalonia

- SIT.Manager.Avalonia/App.axaml
- SIT.Manager.Avalonia/AssemblyInfo.cs
- SIT.Manager.Avalonia/SIT.Manager.Avalonia.csproj
- SIT.Manager.Avalonia/ViewModels/MainViewModel.cs
- SIT.Manager.Avalonia/Views/MainView.axaml
I kinda hate how the bar looks tbh but idk how to change it
> Add update checks

- SIT.Manager.Updater/Program.cs
> Change updater URL to new repo

- SIT.Manager.Avalonia/Views/MainWindow.axaml
- SIT.Manager.Avalonia/Views/MainWindow.axaml.cs
> Fix fullscreen issue by removing custom title bar

- SIT.Manager.Avalonia/ManagedProcess/IAkiServerService.cs
- SIT.Manager.Avalonia/Services/AkiServerService.cs
- SIT.Manager.Avalonia/ViewModels/ServerPageViewModel.cs
- SIT.Manager.Avalonia/Views/ServerPage.axaml.cs
Should resolve #22 
I think this is the nicest way of doing it; I couldn't come up with any other way of handling it at least.
> Preserve server log

- SIT.Manager.Avalonia/Services/AkiServerService.cs
- SIT.Manager.Avalonia/ViewModels/ServerPageViewModel.cs
Remove old irrelevant detection code
> Fix server detecting

- SIT.Manager.Avalonia/Localization/zh-CN.axaml
- SIT.Manager.Avalonia/Localization/zh-HK.axaml
- SIT.Manager.Avalonia/Localization/zh-TW.axaml
Add zh-CN zh-HK zh-TW localizations (Need [PR #50](https://github.com/stayintarkov/SIT.Manager.Avalonia/pull/50))
> Add Chinese localizations (Need PR #50)

- SIT.Manager.Avalonia/Localization/ru-RU.axaml
- SIT.Manager.Avalonia/Localization/uk-UA.axaml
literally forgot to update also Linux localization settings for those languages. Sorry...
> Updated uk-UA, ru-RU missing keys.

- SIT.Manager.Avalonia/Services/LocalizationService.cs
- SIT.Manager.Avalonia/Services/ManagerConfigService.cs
> Remove need for check locale availability function in manager config

- SIT.Manager.Avalonia/App.axaml
Somehow missed this during the resolve..
> Remove missed reference

- SIT.Manager.Avalonia/ViewModels/PlayPageViewModel.cs
This should hopefully protect against mistyped paths and the such
> Add manager crash protection for linux launching

- .editorconfig
- SIT.Manager.Avalonia.sln
> add editorconfig

- SIT.Manager.Avalonia/Classes/TarkovRequesting.cs
Fix the ping server function so you don't have to have the EFT Install path set for it to work
> Fix server pinging 

- SIT.Manager.Avalonia/ViewModels/ToolsPageViewModel.cs
Later versions of SIT use com.stayintarkov now. Not sure whether the use of a hashset is worth it looking back...
> Fix Opening SIT Config

- SIT.Manager.Avalonia/Services/AkiServerService.cs
> handle 0 ip

- SIT.Manager.Avalonia/ViewModels/SettingsPageViewModel.cs
- SIT.Manager.Avalonia/Views/SettingsPage.axaml
I just found out that you can do this which I think is nicer than how we currently show it.
> A nicer way of handling showing linux settings

- SIT.Manager.Avalonia/App.axaml.cs
- SIT.Manager.Avalonia/Interfaces/IDiagnosticService.cs
- SIT.Manager.Avalonia/Localization/en-US.axaml
- SIT.Manager.Avalonia/Localization/ru-RU.axaml
- SIT.Manager.Avalonia/Localization/uk-UA.axaml
- SIT.Manager.Avalonia/Localization/zh-CN.axaml
- SIT.Manager.Avalonia/Localization/zh-HK.axaml
- SIT.Manager.Avalonia/Localization/zh-TW.axaml
- SIT.Manager.Avalonia/Models/DiagnosticsOptions.cs
- SIT.Manager.Avalonia/Services/DiagnosticService.cs
- SIT.Manager.Avalonia/ViewModels/Dialogs/SelectLogsDialogViewModel.cs
- SIT.Manager.Avalonia/ViewModels/ToolsPageViewModel.cs
- SIT.Manager.Avalonia/Views/Dialogs/SelectLogsDialog.axaml
- SIT.Manager.Avalonia/Views/Dialogs/SelectLogsDialog.axaml.cs
- SIT.Manager.Avalonia/Views/ToolsPage.axaml
Adds a new button on the tools page to generate a diagnostics zip containing the selected files
> Add new log generator button

- SIT.Manager/Services/AkiServerService.cs
This is just an improvement until the play page overhaul comes
> Implement a poor woman's exp backoff

- SIT.Manager/Services/LocalizationService.cs
One line of code, solves millions of issues.
Resolving: #142
> Just fixed localization not loading in the settings.

- SIT.Manager/Services/AkiServerService.cs
This will abort after 2 minutes of server starting. If your server takes longer than 2 minutes rethink your life choices.
> Add new startup system

- SIT.Manager/Models/ManagerConfig.cs
- SIT.Manager/Services/Install/InstallerService.cs
Cache and reduce frequency of SIT update checks to once per hour so that we are less likely to get rate limited 😄
> Reduce frequency of SIT update checks

- SIT.Manager/ViewModels/ServerPageViewModel.cs
- SIT.Manager/Views/MainWindow.axaml.cs
Allows the server to be stopped while it's still starting up.
Will resolve #155
> Enable stopping server while it's still starting

- SIT.Manager/Models/ModInfo.cs
- SIT.Manager/Services/ModService.cs
Adds support for patchers
Fixes 2 bad config paths usage
Related changes: https://github.com/stayintarkov/SIT-Mod-Ports/pull/38
> Add support for BepInEx patchers

- SIT.Manager/Services/AppUpdaterService.cs
Use a link that will actually work for linux
> Fix Update Url

- .github/workflows/Create-Release.yml
- .github/workflows/dotnet-desktop.yml
- SIT.Manager.sln
Create an action which will generate a release for us so no more building anything locally and is now just the click of a button😄
Also:
- Switch the current action over to use linux so that it works quicker 
- Get the current action building for both linux and windows.
- Have the current action only build debug versions as they are all we really need from it
> Create Release action

- SIT.Manager/Services/DiagnosticService.cs
HOW did i not implement this???
> Actually perform log cleansing

- SIT.Manager/ViewModels/PlayPageViewModel.cs
Hopefully will fix crashes from last release?
> Update version check for play

- SIT.Manager/ViewModels/MainViewModel.cs
This should fix peoples manager crashing when an update fail checks
> Add update error catching

- SIT.Manager/Interfaces/IInstallerService.cs
- SIT.Manager/Services/AppUpdaterService.cs
- SIT.Manager/Services/Install/InstallerService.cs
- SIT.Manager/ViewModels/Installation/SelectViewModel.cs
- SIT.Manager/ViewModels/MainViewModel.cs
> reimplemented check update condition, fixed SIT update check.

- README.md
- SIT.Manager/App.axaml.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Models/ManagerConfig.cs
- SIT.Manager/Services/DiagnosticService.cs
- SIT.Manager/Services/Install/InstallerService.cs
- SIT.Manager/ViewModels/Dialogs/SelectLogsDialogViewModel.cs
- SIT.Manager/ViewModels/Installation/ConfigureSitViewModel.cs
- SIT.Manager/ViewModels/MainViewModel.cs
- SIT.Manager/ViewModels/ToolsPageViewModel.cs
- SIT.Manager/Views/Dialogs/SelectLogsDialog.axaml.cs
- SIT.Manager/Views/Installation/ConfigureSitView.axaml
- SIT.Manager/Views/MainView.axaml
- SIT.Manager/Views/MainView.axaml.cs
- SIT.Manager/Views/ServerPage.axaml
Fixes hopefully all the remaining issues with updating
> All the fixes

- SIT.Manager/ViewModels/ServerPageViewModel.cs
I like these bugs they're easy to find - will resolve #191
> Fix server page incorrect button text

- SIT.Manager/Services/DiagnosticService.cs
oldest logs were attached to the zip, woopsie daisy
> fix server logs selection in diagnostics.zip

- SIT.Manager.Desktop/SIT.Manager.Desktop.csproj
Probably an idea with all these changes coming on next release to have it be bumped up a minor version
> Bump manager version up

- SIT.Manager/Interfaces/IDiagnosticService.cs
- SIT.Manager/Services/DiagnosticService.cs
Tested to scrub non-private IPv4s.
Not sure how you want to architect this, I'm just passing a bool around.
Using xx.xx.xx.xx to make it clear we removed an IP for easier parsing later.
> scrub ipv4s harder

- SIT.Manager/ViewModels/Play/CharacterSummaryViewModel.cs
- SIT.Manager/Views/Play/CharacterSummaryView.axaml
The icons are a little crispy for some reason. I assume it's due to how the bitmaps are being scaled but I can address that at a later date
> Implement pulling side icons from server

- SIT.Manager/Interfaces/ManagedProcesses/ITarkovClientService.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Services/ManagedProcesses/TarkovClientService.cs
- SIT.Manager/ViewModels/Play/CharacterSummaryViewModel.cs
- SIT.Manager/Views/Installation/ConfigureSitView.axaml
Fix the bookmarking system saving your details and being unable to edit them when trying to connect.
Always show the path selector to set your SIT install location when installing
Forgot to mention this will resolve #209
> Improvement and Fix

- SIT.Manager/Interfaces/ICachingService.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Services/Caching/CachingService.cs
- SIT.Manager/Services/Caching/OnDiskCachingProvider.cs
- SIT.Manager/ViewModels/Installation/ConfigureSitViewModel.cs
- SIT.Manager/ViewModels/PlayPageViewModel.cs
- SIT.Manager/Views/PlayPage.axaml
Hopefully this'll detect if you try and install SIT into an existing SPT install and stop you.
Also fix an issue in the OnDisk caching and then use it to remember the last used connection type on the play page to load that when you next startup the launcher
> More improvements

- SIT.Manager/Interfaces/IAkiServerRequestingService.cs
- SIT.Manager/Interfaces/ManagedProcesses/ITarkovClientService.cs
- SIT.Manager/Models/Aki/AkiCharacter.cs
- SIT.Manager/Services/AkiServerRequestingService.cs
- SIT.Manager/Services/ManagedProcesses/TarkovClientService.cs
- SIT.Manager/ViewModels/Play/CharacterSummaryViewModel.cs
- SIT.Manager/ViewModels/Play/DirectConnectViewModel.cs
Resolve #212 
Manager won't randomly reset the config anymore... probably 😄
> remove circular dependency

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Services/ModService.cs
- SIT.Manager/Views/Installation/SelectView.axaml
Update the text on the install selection page to make it clearer what is happening on that page, also allow an option to skip the compatibility check on mods by using '*'.
> Text update

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/ToolsPageViewModel.cs
- SIT.Manager/Views/Installation/SelectView.axaml
- SIT.Manager/Views/MainView.axaml
- SIT.Manager/Views/ToolsPage.axaml
Add an open server folder function to the tools page, and also fix the text display on the select install page so it diplays correctly, and the end install button now works as it should
> I'm really special

- SIT.Manager/Services/Install/InstallerService.cs
Adds the ability for the installer to install the SIT.WildSpawnType.PrePatcher.dll (if it exists in download zip) into the BepInEx/Patchers folder
> Add installation of SIT.WildSpawnType.PrePatcher.dll

- SIT.Manager/Views/InstallPage.axaml
Will resolve #248 by providing a nicer background to the stepper.
Likely to need #238 for it to actually look good as I based the color for the background off what we have that set to.
> Make the stepper clearer

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/Play/CharacterSelectionViewModel.cs
- SIT.Manager/Views/Play/CharacterSelectionView.axaml
Provide a basic filter which is on by default when you have saved profiles to a connected server.
> Filter character selection

- SIT.Manager/Services/Caching/OnDiskCachingProvider.cs
- SIT.Manager/Services/Install/InstallerService.cs
This should hopefully take some load off the servers. Still need to do the same with the downpatcher downloads
> Implement caching for the downpatchers

- SIT.Manager.Desktop/SIT.Manager.Desktop.csproj
Up the manager minor version from 2.2 to 2.3
> Bump manager minor version

- SIT.Manager/Services/Install/InstallerService.cs
Fixes 3 things I notices with the install service:
1. The CleanUpEFTDirectory didn't actually work properly for a fresh install as it was relying on the stored EFT version rather than the target location we were trying to install to.
2. Progress for the download would get reported as 1 at the end when it should be 100.
3. Removed the call to CopyEftSettings as we already do that elsewhere if the user requested it.
> Fixes for sit install service

- SIT.Manager/Services/Caching/CacheValue.cs
- SIT.Manager/Services/Caching/CachingProviderBase.cs
- SIT.Manager/Services/Caching/ICachingProvider.cs
- SIT.Manager/Services/Caching/InMemoryCachingProvider.cs
- SIT.Manager/Services/Caching/OnDiskCachingProvider.cs
Idk wtf I was doing when I wrote this the first time but this should hopefully fix whatever the hell was going on when we started to use this
> Caching service tweaks

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/Tools/GeneralToolsViewModel.cs
- SIT.Manager/Views/Tools/GeneralToolsView.axaml
Resolve #255 by adding a button to specifically delete the cache from the manager
Also sperate the delete all cache and delete EFT local user cache buttons out to use the space available a bit more.
> Add Manager cache deletion button

- SIT.Manager/Interfaces/IAkiServerRequestingService.cs
- SIT.Manager/Services/AkiServerRequestingService.cs
This shouldn't affect the functionality of the code but makes it much cleaner and easier to work on in the future
> AkiServerRequestingService refactor/cleanup

- SIT.Manager/Services/ManagedProcesses/AkiServerService.cs
- SIT.Manager/Services/ManagedProcesses/ManagedProcess.cs
- SIT.Manager/Services/ManagedProcesses/TarkovClientService.cs
Mostly tidying up the class to make it more readable. This shouldn't affect any functionality. Refactor still to come
> Clean up ManagedProcess and derived classes

- SIT.Manager/Interfaces/IAkiServerRequestingService.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Services/AkiServerRequestingService.cs
- SIT.Manager/Services/Install/InstallerService.cs
- SIT.Manager/Services/ManagedProcesses/AkiServerService.cs
- SIT.Manager/Services/ManagedProcesses/ManagedProcess.cs
- SIT.Manager/Services/ManagedProcesses/TarkovClientService.cs
Managing two branches at once was hurting my brain
> Merge code cleanup into development
