stayintarkov/SIT.Manager.Avalonia

- SIT.Manager.Avalonia/ViewModels/PlayPageViewModel.cs
Because SIT 1.9 doesn't expect the backendUrl to end with a slash, the requests done by SIT contains a double slash and fails. This temporarily address the issue and can be removed when SIT 1.9 is no longer used as SIT 1.10 handles the ending slash.
> Temporary backendUrl fix for SIT 1.9

- SIT.Manager.Avalonia/Services/ManagerConfigService.cs
I was wondering why my credentials kept resetting and it's because I'm stupid. If we didn't specific to remember login when updating the config it would default to false instead of the last used value, meaning any config not explicitly stating to remember would null out saved credentials
> Fix config wiping saved credentials

- SIT.Manager.Avalonia.Desktop/SIT.Manager.Avalonia.Desktop.csproj
Sets the executable icon for Windows builds.
Wasn't sure whether to move the .ico file into the desktop project folder or leave it. Figured leaving it was simpler.
> Add ApplicationIcon entry

- SIT.Manager.Avalonia.Desktop/Program.cs
- SIT.Manager.Avalonia/Controls/ActivatableUserControl.cs
- SIT.Manager.Avalonia/SIT.Manager.Avalonia.csproj
- SIT.Manager.Avalonia/ViewModels/Dialogs/SelectDowngradePatcherMirrorDialogViewModel.cs
- SIT.Manager.Avalonia/ViewModels/Dialogs/SelectEditionDialogViewModel.cs
- SIT.Manager.Avalonia/ViewModels/Dialogs/SelectVersionDialogViewModel.cs
- SIT.Manager.Avalonia/ViewModels/LocationEditorViewModel.cs
- SIT.Manager.Avalonia/ViewModels/MainViewModel.cs
- SIT.Manager.Avalonia/ViewModels/ModsPageViewModel.cs
- SIT.Manager.Avalonia/ViewModels/PlayPageViewModel.cs
- SIT.Manager.Avalonia/ViewModels/ServerPageViewModel.cs
- SIT.Manager.Avalonia/ViewModels/SettingsPageViewModel.cs
- SIT.Manager.Avalonia/ViewModels/ToolsPageViewModel.cs
- SIT.Manager.Avalonia/ViewModels/ViewModelBase.cs
- SIT.Manager.Avalonia/Views/MainView.axaml
- SIT.Manager.Avalonia/Views/MainView.axaml.cs
- SIT.Manager.Avalonia/Views/ModsPage.axaml.cs
- SIT.Manager.Avalonia/Views/ServerPage.axaml.cs
A problem I kept running into while doing the new install page was the way view activation was triggered. So I removed the dependency on ReactiveUI as that was pretty much all we used it for and added a way to do it using just CommunityMVVM.
Surprisingly the only thing this broke was the settings button translation in the main view, so converted the settings button to be able to be translated in XAML. Haven't seen any other problems with this but let me know 😄
> Activate views differently

- SIT.Manager/Extentions/HttpClientExtentions.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Services/FileService.cs
- SIT.Manager/Services/Install/InstallerService.cs
- SIT.Manager/Services/PickerDialogService.cs
- SIT.Manager/ViewModels/Installation/ConfigureServerViewModel.cs
- SIT.Manager/ViewModels/Installation/InstallViewModel.cs
- SIT.Manager/ViewModels/Installation/PatchViewModel.cs
- SIT.Manager/ViewModels/UpdatePageViewModel.cs
- SIT.Manager/Views/Installation/PatchView.axaml
Fix and improve a few things for installation.
1. Should resolve #129 as the normal downloading value we get is between 0 and 1 but for mega downloads is between 0 and 100, maybe we need to fix the actual root cause which I think is in [HttpClientExtentions.cs](https://github.com/stayintarkov/SIT.Manager.Avalonia/blob/master/SIT.Manager/Extentions/HttpClientExtentions.cs) although we'd then have to go find all the other places we account for this.
2. Should resolve #141 I'm not quite sure who's at fault for this as it was the actual file picker from Avalonia which we use throws an Argument Exception if you try and select a directory which doesn't exist, I kind of assumed it just returned null. So now if you do that the manager won't crash.
3. Make downloads from Mega actually use the file …
> Installation fixes

- SIT.Manager.Desktop/AssemblyInfo.cs
- SIT.Manager.Desktop/SIT.Manager.Desktop.csproj
- SIT.Manager/SIT.Manager.csproj
- SIT.Manager/Services/AppUpdaterService.cs
- SIT.Manager/ViewModels/SettingsPageViewModel.cs
This should make versioning in CI/CD builds much easier 😄 
Also applies the copyright properly as shown in the screenshot below, the left is the current release and the right is with these changes (please ignore the version number I was checking I didn't break the update checking).
> Help with versioning

- SIT.Manager/ViewModels/Installation/ConfigureSitViewModel.cs
Added a simple ValidateConfiguration call at the end of FetchVersionAndMirrorMatrix because it was bugging me :)
This now allows users to simply click next on the install instead of having to change mirror (even if the mirror they want to use is selected).
> Allow users to use default mirror on download

- .github/workflows/Create-Release.yml
Should ensure that only one release draft ever gets created by putting the release creation into a seperate job.
> Ensure only one draft of release gets created

- SIT.Manager/Services/ModService.cs
Create the directory that it should rather than creating a directory of the filename
Currently creates the directory below rather than just ensuring that the one it's trying to copy to exists:
> Properly fix configmanager installation

- SIT.Manager/Models/ManagerConfig.cs
- SIT.Manager/Services/AppUpdaterService.cs
- SIT.Manager/Services/Install/InstallerService.cs
- SIT.Manager/Services/ManagerConfigService.cs
- SIT.Manager/ViewModels/ServerPageViewModel.cs
Wrapped up a couple of things into this
1. Cache the last check time for manager update checking and only do this once an hour. Does potentially mean a user could start the manager get told there is an update, restart the manager and then not get told about the update at the moment but will dramatically reduce the amount of usage of the api. However might mean we want a button somewhere that forces a check or something?
2. Fix the SIT update check so that it actually will check for an update now.
3. Cache the json serializer options for the manager config as we use them a lot so no need to recreate it constantly.
4. Should hopefully fix the weird issue I saw earlier when trying to install mods.
> Caching in some places

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/Installation/ConfigureServerViewModel.cs
- SIT.Manager/ViewModels/Installation/ConfigureSitViewModel.cs
- SIT.Manager/ViewModels/MainViewModel.cs
- SIT.Manager/Views/Installation/ConfigureServerView.axaml
- SIT.Manager/Views/Installation/ConfigureSitView.axaml
Add an error on the server install page if there is no version available to install. Also prevent a crash from occuring if the user navigates to the SIT install page with no internet.
> Prevent crash on launching with no internet

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Models/Config/ManagerConfig.cs
- SIT.Manager/Services/FileService.cs
- SIT.Manager/Services/Install/InstallerService.cs
- SIT.Manager/Services/ManagedProcesses/TarkovClientService.cs
- SIT.Manager/Services/ModService.cs
- SIT.Manager/ViewModels/Installation/SelectViewModel.cs
- SIT.Manager/ViewModels/ModsPageViewModel.cs
- SIT.Manager/ViewModels/Play/DirectConnectViewModel.cs
- SIT.Manager/ViewModels/Settings/EftViewModel.cs
- SIT.Manager/ViewModels/ToolsPageViewModel.cs
- SIT.Manager/Views/Settings/EftView.axaml
Should hopefully make the EFT path setting much clearer, and also harder to select the BSG EFT install by mistake now.
I think this is the nicest way of displaying it and doing it but am open to any suggestions.
> Make EFT Path in settings clearer

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/MainViewModel.cs
- SIT.Manager/ViewModels/Play/CharacterSelectionViewModel.cs
- SIT.Manager/ViewModels/Play/CharacterSummaryViewModel.cs
- SIT.Manager/ViewModels/Play/DirectConnectViewModel.cs
- SIT.Manager/ViewModels/Settings/EftViewModel.cs
- SIT.Manager/Views/Play/ServerSummaryView.axaml
Should prevent user from accessing functions which require SIT to be installed without having it actually installed. Also has toned down the loading indicator on the server and provided more feedback on when the sever is actually down.
> Other things

- SIT.Manager/Services/ManagedProcesses/TarkovClientService.cs
Make non valid json only apply on linux and remove the trailing slash from launch arguments as that seemed to cause some strange issues sometimes on launching.
> Test Fixes

- SIT.Manager.Desktop/Program.cs
- SIT.Manager/App.axaml.cs
- SIT.Manager/SIT.Manager.csproj
- SIT.Manager/ViewModels/Play/DirectConnectViewModel.cs
Closes #170 
This PR adds the launch params described in the issue.
--address (-a): sets the server address to connect to, if omitted this will start a local server
--username (-u): sets the username of the account to login with
--password (-p): sets the password of the account to login with
> Add Launch Params

- SIT.Manager.Desktop/Program.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Models/Config/ManagerConfig.cs
- SIT.Manager/Services/Install/InstallerService.cs
- SIT.Manager/ViewModels/Installation/ConfigureSitViewModel.cs
- SIT.Manager/ViewModels/MainViewModel.cs
- SIT.Manager/ViewModels/ModsPageViewModel.cs
- SIT.Manager/ViewModels/Settings/LauncherViewModel.cs
- SIT.Manager/Views/MainView.axaml
- SIT.Manager/Views/Settings/LauncherView.axaml
Convert the developer mode we created a little while ago in the launcher to a test mode which will only show prerelease builds of SIT client to users. So that when we want people to test a release of SIT they can enable that and install it then, otherwise they will only have normal full releases of SIT.
> Convert Developer mode to Test Mode

- SIT.Manager/ViewModels/Play/DirectConnectViewModel.cs
- SIT.Manager/Views/Play/DirectConnectView.axaml
Does 2 things:
- Hide the `Start Server and Connect button`, if no server path set to resolve #239 
- Hide the `Start Server and Connect button` if the local server is started/running to at least partly resolve #216
> Hide start server button

- SIT.Manager/App.axaml.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/MainViewModel.cs
- SIT.Manager/ViewModels/SettingsPageViewModel.cs
- SIT.Manager/Views/MainView.axaml
- SIT.Manager/Views/MainView.axaml.cs
- SIT.Manager/Views/SettingsPage.axaml
Moves the manager version string from where it currently is on the settings page as shown below to be always visible but tucked away in the bottom left corner.
Before;
After:
> Move the manager version string to be always visible

- SIT.Manager/Services/Install/InstallerService.cs
Fixes a problem with where files are located in the release directory, the manager will now search recursively through subdirectories to find the files we are looking for.
> Allow the manager to still install the currently available release

- SIT.Manager/Interfaces/IModService.cs
- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Models/Installation/InstallProcessState.cs
- SIT.Manager/Services/ModService.cs
- SIT.Manager/ViewModels/Installation/ConfigureSitViewModel.cs
- SIT.Manager/ViewModels/Installation/InstallViewModel.cs
- SIT.Manager/ViewModels/ModsPageViewModel.cs
- SIT.Manager/Views/Installation/ConfigureSitView.axaml
Rather than having the option to install configuration manager now we just do it, but also cache the downloaded dll for a day just in case they run multiple installs this'll help prevent hitting that GitHub api rate limit.
> Automagically install config manager always

- SIT.Manager/Services/Install/InstallerService.cs
Something seems to be broken with caching strings? I'll need to take some time to look into this. For now I'm rolling back our usage of it
> Revert caching

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/Installation/ConfigureSitViewModel.cs
- SIT.Manager/ViewModels/Play/ServerSummaryViewModel.cs
- SIT.Manager/Views/Installation/ConfigureSitView.axaml
- SIT.Manager/Views/Settings/EftView.axaml
A few fixes and tweaks to hopefully improve things:
1. Reduce the excessive number of pings to bookmarked servers as it would be pinging the server even when the view wasn't activated
2. Add a first super basic check for installing to OneDrive should resolve #245
3. Fix the manager getting confused and showing multiple text over each other when looking at EFT settings
4. Show a more helpful error message when unable to determine a SIT version to install.
> Various Fixes

- SIT.Manager/Services/Caching/CachingProviderBase.cs
- SIT.Manager/Services/Caching/InMemoryCachingProvider.cs
- SIT.Manager/Services/Caching/OnDiskCachingProvider.cs
Switch TryGet<T> to compare with ```CacheValue<T>.NoValue``` as this is what the Get<T> functions implemented by InMemoryCachingProvider & OnDiskCachingProvider mostly returned 
Then change the one case where OnDiskCachingProvider returned ```CacheValue<T>.Null```
> Be consistent with in memory and on disk caches

- SIT.Manager/Theme/Styles/Button.axaml
- SIT.Manager/Theme/Theme.axaml
- SIT.Manager/Views/Installation/ConfigureServerView.axaml
- SIT.Manager/Views/Installation/ConfigureSitView.axaml
Essentially apply the same theming ideas to these buttons as there is almost everywhere else. It doesn't seem to work brilliantly but I think that's more down to some things in FluentAvalonia getting in the way, can look into those later.
> Make the buttons on the configure installs pages more unified

- SIT.Manager/Services/Caching/OnDiskCachingProvider.cs
- SIT.Manager/ViewModels/PlayPageViewModel.cs
Make the Filestream in the OnDiskCachingProvider use a using statement so it clears itself from being used by the time we need to use the file again.
> Make OnDiskCachingProvider Filestream safe.

- SIT.Manager/ViewModels/Play/CharacterSelectionViewModel.cs
- SIT.Manager/ViewModels/Play/CharacterSummaryViewModel.cs
Duplicate entries end up looking like this (passwords blanked out):
This was caused by CharacterSummaryViewModel having the rememberLogin defaulting to true - if the profile was already saved the login box is not shown and this variable then remains true, which causes the code that checks to see if the connection to EFT was successful and rememberLogin was also true to add the profile to the config.  This variable has now been set to false.
Have also added a clean up routine in CharacterSelectionViewModel that removes all duplicate saved profiles (if there are any).  It chooses the profile to keep by grouping by username and password, then selecting either the first entry with a ProfileID or the first entry if there are no Profile ID's.  All profiles for that username/password are then …
> There is an issue where saving a profile causes duplicates in ManagerConfig.json

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/Play/CharacterSummaryViewModel.cs
- SIT.Manager/Views/Play/CharacterSummaryView.axaml
Useful if the PC is shared or if you, for whatever reason, need to share your SIT install.
New button only displays if the profile is a saved profile and updated localization files (using online translate tools) to add button text.
Character selection with a saved profile (remember me ticked on login dialog):
After clicking on logout:
ManagerConfig.json file is updated to remove the saved profile after clicking so that the next time the manager is started the profile is still logged out.
> Added a logout button so that a "saved profile" can be forgotten.

- SIT.Manager/ViewModels/Play/CharacterSummaryViewModel.cs
- SIT.Manager/Views/Play/CharacterSummaryView.axaml
Updated the CharacterSummaryViewModel to expose an additional property _canLaunch (with an Observable generated instance) which is set to either true or false (defaults to true) depending on the state of _tarkovClientService.RunningStateChanged.
An event handler is attached to listen for RunningStateChanged events, if the state is either Starting or Running _canLaunch is set to false, the other states (NotRunning and StoppedUnexpectedly) set this to true.
The CharacterSummaryView.axaml's command button (Login or Play) has the property IsEnabled bound to this new property - in doing this all buttons are enabled or disabled when EFT is started/stopped. This property is changed on the UI thread with the use of Dispatcher.UIThread.Invoke().
The upshot of this change is that the UI now behaves …
> Enable and Disable the Login and Play buttons on Character Summary view dependent on EFT's running state.

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/Models/Aki/AkiServer.cs
- SIT.Manager/Models/Play/CreateServerDialogResult.cs
- SIT.Manager/ViewModels/Play/CreateServerDialogViewModel.cs
- SIT.Manager/ViewModels/Play/ServerSelectionViewModel.cs
- SIT.Manager/ViewModels/Play/ServerSummaryViewModel.cs
- SIT.Manager/Views/Play/CreateServerDialogView.axaml
- SIT.Manager/Views/Play/CreateServerDialogView.axaml.cs
- SIT.Manager/Views/Play/ServerSummaryView.axaml
Resolve #267 by adding an optional entry in the edit server and add server dialogs to set a nickname for the server.
This nickname overrides whatever the server name is set to and displays that instead, if a user wants to see the real server name again then they just have to unset the nickname by editing the server entry to remove it.
> Implement server nicknaming locally for users

- SIT.Manager/Localization/en-US.axaml
- SIT.Manager/Localization/ru-RU.axaml
- SIT.Manager/Localization/uk-UA.axaml
- SIT.Manager/Localization/zh-CN.axaml
- SIT.Manager/Localization/zh-HK.axaml
- SIT.Manager/Localization/zh-TW.axaml
- SIT.Manager/ViewModels/Tools/NetworkToolsViewModel.cs
- SIT.Manager/Views/Tools/NetworkToolsView.axaml
Resolve #280 by adding the suggested improvements.
> Port checker enhancements

- SIT.Manager/App.axaml.cs
This was carried over from the old manager without question. I see no reason for this to be here and so we're axing it for security
> Remove custom cert delegate
